name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
      - uses: actions/setup-node@v7

      - run: npm install

      - uses: pre-commit/action@v3.0.1
